project:
  type: website
  output-dir: docs

website:
  title: "Josh Goldhaber"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: "All my fav resources!"
      - href: analysis.qmd
        text: "Text Analysis"
      - href: PermutationTest.qmd
        text: "Project 3"
      - text: "Data Visualization"
        menu:
          - text: "Fifa Data"
            href: FifaData.qmd
          - text: "Fast Food Cals"
            href: FastFoodCals.qmd

format:
  html:
    theme: flatly
    dark: solar
    css: styles.css
    toc: true
    page-layout: full
