---
title: "About This Website"
format:
  html:
    code-fold: true
    theme: flatly
---

# About This Website

Welcome to my data science portfolio website! This site serves as a comprehensive showcase of my work, projects, and insights in the field of data science. Whether you are a fellow data enthusiast, a potential collaborator, or simply curious about the fascinating world of data, I hope you find the content here engaging and informative.

## Purpose

The primary goal of this website is to document and share my journey in data science. It includes a variety of projects that demonstrate my skills in data analysis, visualization, statistical modeling, and machine learning. Each project is accompanied by detailed explanations, code snippets, and visualizations to provide a clear understanding of the methodologies and insights derived.

## What You’ll Find Here

### 1. **Projects**
- **Permutation Testing**: An in-depth analysis of gold and silver price volatility using permutation tests to uncover differences in underlying market dynamics.
- **Netflix String Data Analysis**: A text analysis project exploring patterns in Netflix titles using regular expressions and thematic visualizations.
- **FIFA Audience Insights**: A statistical exploration of FIFA World Cup TV audience data, highlighting trends and relationships.
- **Fast Food Calories**: A comparative analysis of calorie content across popular fast-food chains, visualized for easy interpretation.
- **SQL Data Analysis**: An exploration of traffic-stops data with SQL.
- **Ethics Analysis**: A comprehensive overview of the ethicality of the Northpointe COMPAS algorithm, including statistical evidence and even a personal paper on the subject.

## Common Libraries Used

This website is built using **Quarto**, a powerful tool for creating dynamic and interactive documents. The projects and analyses leverage a variety of R packages, including:
- **tidyverse**: For data manipulation and visualization.
- **ggplot2**: For creating elegant and informative plots.
- **infer**: For statistical inference and hypothesis testing.
- **quantmod**: For financial data analysis.
