<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joshua Goldhaber">

<title>ECON 091 Final Project: Cook County Sentencing – Josh Goldhaber</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bdd2aebeb936dcddaa5f935a5de481c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Josh Goldhaber</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./analysis.html"> 
<span class="menu-text">Text Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PermutationTest.html"> 
<span class="menu-text">Permutation Test</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Ethics.html"> 
<span class="menu-text">Ethics of COMPAS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./SQL.html"> 
<span class="menu-text">Traffic Stops with SQL</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-visualization" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data Visualization</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-visualization">    
        <li>
    <a class="dropdown-item" href="./FifaData.html">
 <span class="dropdown-text">Fifa Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./FastFoodCals.html">
 <span class="dropdown-text">Fast Food Cals</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./FinalPresentation.html"> 
<span class="menu-text">Final Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./EconStatsFinal.html" aria-current="page"> 
<span class="menu-text">Econ Stats Final Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-question" id="toc-research-question" class="nav-link active" data-scroll-target="#research-question">Research question</a>
  <ul class="collapse">
  <li><a href="#map-cook-county" id="toc-map-cook-county" class="nav-link" data-scroll-target="#map-cook-county">Map: Cook County</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">1. Data</a>
  <ul class="collapse">
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#b-describing-the-data" id="toc-b-describing-the-data" class="nav-link" data-scroll-target="#b-describing-the-data">1(b) Describing the data</a></li>
  <li><a href="#c-descriptive-stats-table-what-stands-out" id="toc-c-descriptive-stats-table-what-stands-out" class="nav-link" data-scroll-target="#c-descriptive-stats-table-what-stands-out">1(c) Descriptive stats table &amp; what stands out</a></li>
  <li><a href="#d-is-there-reason-to-believe-you-have-a-good-research-question-t-test" id="toc-d-is-there-reason-to-believe-you-have-a-good-research-question-t-test" class="nav-link" data-scroll-target="#d-is-there-reason-to-believe-you-have-a-good-research-question-t-test">1(d) Is there reason to believe you have a good research question? (t-test)</a></li>
  <li><a href="#e-other-relevant-descriptive-statistics-plots" id="toc-e-other-relevant-descriptive-statistics-plots" class="nav-link" data-scroll-target="#e-other-relevant-descriptive-statistics-plots">1(e) Other relevant descriptive statistics (plots)</a></li>
  </ul></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">2. Hypothesis</a>
  <ul class="collapse">
  <li><a href="#a-hypothesis-and-expected-trend" id="toc-a-hypothesis-and-expected-trend" class="nav-link" data-scroll-target="#a-hypothesis-and-expected-trend">2(a) Hypothesis and expected trend</a></li>
  <li><a href="#b-model-specification-why-this-trend" id="toc-b-model-specification-why-this-trend" class="nav-link" data-scroll-target="#b-model-specification-why-this-trend">2(b) Model Specification, why this trend?</a></li>
  <li><a href="#c-what-would-make-you-rejectrespecify" id="toc-c-what-would-make-you-rejectrespecify" class="nav-link" data-scroll-target="#c-what-would-make-you-rejectrespecify">2(c) What would make you reject/respecify?</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression">3. Regression</a>
  <ul class="collapse">
  <li><a href="#a-run-regressions-and-iterate-to-find-the-best-performer" id="toc-a-run-regressions-and-iterate-to-find-the-best-performer" class="nav-link" data-scroll-target="#a-run-regressions-and-iterate-to-find-the-best-performer">3(a) Run regressions and iterate to find the best performer</a>
  <ul class="collapse">
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">Clustering</a></li>
  </ul></li>
  <li><a href="#b-evaluate" id="toc-b-evaluate" class="nav-link" data-scroll-target="#b-evaluate">3(b) Evaluate</a>
  <ul class="collapse">
  <li><a href="#bi-which-model-performs-best-why" id="toc-bi-which-model-performs-best-why" class="nav-link" data-scroll-target="#bi-which-model-performs-best-why">3(b)(i) Which model performs best? Why?</a></li>
  <li><a href="#bii-do-you-trust-your-model-why" id="toc-bii-do-you-trust-your-model-why" class="nav-link" data-scroll-target="#bii-do-you-trust-your-model-why">3(b)(ii) Do you trust your model? Why?</a></li>
  <li><a href="#biii-publication-ready-what-would-you-need" id="toc-biii-publication-ready-what-would-you-need" class="nav-link" data-scroll-target="#biii-publication-ready-what-would-you-need">3(b)(iii) Publication-ready? What would you need?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#tests" id="toc-tests" class="nav-link" data-scroll-target="#tests">4. Tests</a>
  <ul class="collapse">
  <li><a href="#a-what-tests-do-we-need" id="toc-a-what-tests-do-we-need" class="nav-link" data-scroll-target="#a-what-tests-do-we-need">4(a) What tests do we need?</a></li>
  <li><a href="#b-run-them-does-the-model-pass" id="toc-b-run-them-does-the-model-pass" class="nav-link" data-scroll-target="#b-run-them-does-the-model-pass">4(b) Run them + does the model pass?</a>
  <ul class="collapse">
  <li><a href="#corrplot" id="toc-corrplot" class="nav-link" data-scroll-target="#corrplot">Corrplot</a></li>
  <li><a href="#qq-plot" id="toc-qq-plot" class="nav-link" data-scroll-target="#qq-plot">QQ plot</a></li>
  <li><a href="#heteroskedasticity-test" id="toc-heteroskedasticity-test" class="nav-link" data-scroll-target="#heteroskedasticity-test">Heteroskedasticity test</a></li>
  <li><a href="#residual-analysis-for-zero-conditional-mean-assumption" id="toc-residual-analysis-for-zero-conditional-mean-assumption" class="nav-link" data-scroll-target="#residual-analysis-for-zero-conditional-mean-assumption">Residual Analysis for Zero Conditional Mean Assumption</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">5. Conclusions</a>
  <ul class="collapse">
  <li><a href="#a-implications-of-this-model" id="toc-a-implications-of-this-model" class="nav-link" data-scroll-target="#a-implications-of-this-model">5(a) Implications of this model</a></li>
  <li><a href="#b-recommendations" id="toc-b-recommendations" class="nav-link" data-scroll-target="#b-recommendations">5(b) Recommendations</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">5(d)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ECON 091 Final Project: Cook County Sentencing</h1>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joshua Goldhaber </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install and load packages locally</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>,<span class="st">"readr"</span>,<span class="st">"lubridate"</span>,<span class="st">"janitor"</span>,<span class="st">"stargazer"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"corrplot"</span>,<span class="st">"broom"</span>,<span class="st">"scales"</span>,<span class="st">"lmtest"</span>,<span class="st">"sandwich"</span>,<span class="st">"knitr"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># generated by AI </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>to_install <span class="ot">&lt;-</span> pkgs[<span class="sc">!</span>pkgs <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">"Package"</span>]]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(to_install) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">install.packages</span>(to_install)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">91</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># metrics for model comparison (Q3)</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="cf">function</span>(actual, pred) <span class="fu">sqrt</span>(<span class="fu">mean</span>((actual <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>mae  <span class="ot">&lt;-</span> <span class="cf">function</span>(actual, pred) <span class="fu">mean</span>(<span class="fu">abs</span>(actual <span class="sc">-</span> pred), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="research-question" class="level1">
<h1>Research question</h1>
<p><strong>Research question:</strong><br>
Using Cook County records where the case has a current sentence and we focus on the primary charge, how well can we predict sentence length (in years) from judge, race, gender, and legally-relevant controls (offense category, charge class, sentence type, charge count, age, and case length)? After accounting for those controls, do race and gender still show meaningful associations with sentence length?</p>
<section id="map-cook-county" class="level2">
<h2 class="anchored" data-anchor-id="map-cook-county">Map: Cook County</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="CookMap.png" class="img-fluid figure-img"></p>
<figcaption>Cook County map</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="data" class="level1">
<h1>1. Data</h1>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1(a): Load dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>sent <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CookCountySentencing.csv"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">guess_max =</span> <span class="dv">100000</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(sent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 305,884
Columns: 41
$ case_id                           &lt;dbl&gt; 130011887122, 130011887122, 13001188…
$ case_participant_id               &lt;dbl&gt; 1.030438e+12, 1.030438e+12, 1.030438…
$ received_date                     &lt;chr&gt; "1984 Aug 15 12:00:00 AM", "1984 Aug…
$ offense_category                  &lt;chr&gt; "PROMIS Conversion", "PROMIS Convers…
$ primary_charge_flag               &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ charge_id                         &lt;dbl&gt; 3.589259e+12, 3.589267e+12, 3.589710…
$ charge_version_id                 &lt;dbl&gt; 59562543694, 50324211856, 6758690200…
$ disposition_charged_offense_title &lt;chr&gt; "FIRST DEGREE MURDER", "HOME INVASIO…
$ charge_count                      &lt;dbl&gt; 2, 14, 4, 5, 13, 13, 15, 15, 16, 1, …
$ disposition_date                  &lt;chr&gt; "2014 Dec 17 12:00:00 AM", "2014 Dec…
$ disposition_charged_chapter       &lt;chr&gt; "38", "38-12-11-A(2)", "38", "38", "…
$ disposition_charged_act           &lt;chr&gt; "-", NA, "-", "-", NA, NA, NA, NA, N…
$ disposition_charged_section       &lt;chr&gt; "9-1(a)(2)", NA, "9-1(a)(3)", "9-1(a…
$ disposition_charged_class         &lt;chr&gt; "X", "X", "X", "X", "X", "X", "X", "…
$ disposition_charged_aoic          &lt;chr&gt; "0000001607", "0000001847", "0000001…
$ charge_disposition                &lt;chr&gt; "Nolle On Remand", "Nolle On Remand"…
$ charge_disposition_reason         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ sentence_judge                    &lt;chr&gt; "John  Mannion", "John  Mannion", "J…
$ sentence_court_name               &lt;chr&gt; "District 6 - Markham", "District 6 …
$ sentence_court_facility           &lt;chr&gt; "Markham Courthouse", "Markham Court…
$ sentence_phase                    &lt;chr&gt; "Original Sentencing", "Original Sen…
$ sentence_date                     &lt;chr&gt; "1986 Jun 02 12:00:00 AM", "1986 Jun…
$ sentence_type                     &lt;chr&gt; "Conversion", "Conversion", "Convers…
$ current_sentence_flag             &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, FALSE,…
$ commitment_type                   &lt;chr&gt; "Natural Life", "Illinois Department…
$ commitment_term                   &lt;chr&gt; NA, "030", NA, NA, "30", "030", "30"…
$ commitment_unit                   &lt;chr&gt; NA, "Year(s)", NA, NA, "Year(s)", "Y…
$ length_of_case_in_days            &lt;dbl&gt; 619, 619, 619, 619, 10982, 619, 1098…
$ age_at_incident                   &lt;dbl&gt; 27, 27, 27, 27, 27, 27, 27, 27, 27, …
$ race                              &lt;chr&gt; "Black", "Black", "Black", "Black", …
$ gender                            &lt;chr&gt; "Male", "Male", "Male", "Male", "Mal…
$ incident_city                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ incident_begin_date               &lt;chr&gt; "1984 Aug 09 12:00:00 AM", "1984 Aug…
$ incident_end_date                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ law_enforcement_agency            &lt;chr&gt; "CHICAGO POLICE DEPT", "CHICAGO POLI…
$ law_enforcement_unit              &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ arrest_date                       &lt;chr&gt; "1984 Aug 15 12:00:00 AM", "1984 Aug…
$ felony_review_date                &lt;chr&gt; "1984 Aug 15 12:00:00 AM", "1984 Aug…
$ felony_review_result              &lt;chr&gt; "Charge(S) Approved", "Charge(S) App…
$ arraignment_date                  &lt;chr&gt; "1984 Sep 21 12:00:00 AM", "1984 Sep…
$ updated_offense_category          &lt;chr&gt; "PROMIS Conversion", "PROMIS Convers…</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sent <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">rows =</span> <span class="fu">n</span>(), <span class="at">cols =</span> <span class="fu">ncol</span>(sent))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
    rows  cols
   &lt;int&gt; &lt;int&gt;
1 305884    41</code></pre>
</div>
</div>
</section>
<section id="b-describing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="b-describing-the-data">1(b) Describing the data</h2>
<p>https://datacatalog.cookcountyil.gov/Legal-Judicial/Sentencing/tg8v-tm6u/about_data</p>
<p>The data used in this project comes from the Cook County Sentencing dataset, published on the Cook County Open Data Portal and maintained by the Cook County State’s Attorney’s Office (CCSAO), in fact, the office in which my Mother, Catherine Goldhaber used to work in. Cook is a large county in Illinois that covers the Chicagoland area and all of its surrounding suburbs. The dataset consists of administrative court records documenting sentences imposed following convictions in Cook County, Illinois. Each observation corresponds to a single charged offense that received a sentence, rather than a unique individual, meaning defendants with multiple sentenced charges may appear multiple times in the data.</p>
<p>The data are collected as part of the county’s routine judicial and prosecutorial record-keeping process, and republished quarterly. Information is recorded during the normal processing of criminal cases and then released publicly to promote transparency in the criminal justice system.</p>
<p>The dataset is not randomly sampled. Instead, it represents a population dataset of sentencing events recorded by Cook County courts over the covered time period. As a result, inference from this dataset should be interpreted as descriptive of Cook County sentencing practices rather than as estimates from a random sample.</p>
<p>There are several important potential sources of bias. First, the dataset includes only cases that resulted in a sentence, excluding arrests that did not lead to conviction, cases dismissed, or cases resolved through diversion programs. This creates selection bias, as the data reflect later stages of the criminal justice process rather than initial charging or policing decisions. Second, key determinants of sentencing—such as prior criminal history, plea bargaining details, sentencing guideline ranges, quality of legal representation, and evidentiary strength—are not fully observed, raising concerns about omitted variable bias in regression analysis. Third, demographic variables such as race and gender may be subject to misclassification or missingness, as they are administratively.</p>
<p>In terms of representativeness, the dataset is representative of sentenced cases in Cook County, but it is not representative of all criminal defendants, all arrests, or sentencing practices outside Cook County. Because Cook County is a large and diverse urban jurisdiction, patterns observed here may differ substantially from those in suburban, rural, or out-of-state courts. Consequently, conclusions from this analysis should be interpreted as applying specifically to Cook County sentencing outcomes, rather than to the U.S. criminal justice system as a whole.</p>
</section>
<section id="c-descriptive-stats-table-what-stands-out" class="level2">
<h2 class="anchored" data-anchor-id="c-descriptive-stats-table-what-stands-out">1(c) Descriptive stats table &amp; what stands out</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1(c): Clean data and create variables (including outcome)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcome = years_sentenced</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>sent_clean <span class="ot">&lt;-</span> sent <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># your intended analytic sample</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(current_sentence_flag <span class="sc">==</span> <span class="cn">TRUE</span>, primary_charge_flag <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># numeric coercions</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">charge_count =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(charge_count)),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">length_of_case_in_days =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(length_of_case_in_days)),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_at_incident =</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(age_at_incident)),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># parse commitment term into a numeric when possible</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">commitment_term_num =</span> readr<span class="sc">::</span><span class="fu">parse_number</span>(<span class="fu">as.character</span>(commitment_term)),</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert commitment to DAYS (keep only true time units)</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">commitment_days =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>      commitment_unit <span class="sc">==</span> <span class="st">"Hours"</span>   <span class="sc">~</span> commitment_term_num <span class="sc">/</span> <span class="dv">24</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>      commitment_unit <span class="sc">==</span> <span class="st">"Days"</span>    <span class="sc">~</span> commitment_term_num,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>      commitment_unit <span class="sc">==</span> <span class="st">"Weeks"</span>   <span class="sc">~</span> commitment_term_num <span class="sc">*</span> <span class="dv">7</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>      commitment_unit <span class="sc">==</span> <span class="st">"Months"</span>  <span class="sc">~</span> commitment_term_num <span class="sc">*</span> <span class="fl">30.44</span>,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>      commitment_unit <span class="sc">==</span> <span class="st">"Year(s)"</span> <span class="sc">~</span> commitment_term_num <span class="sc">*</span> <span class="dv">365</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>                         <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># outcome in years</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">years_sentenced =</span> commitment_days <span class="sc">/</span> <span class="dv">365</span>,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clean race (regex approach; keep Missing/Other buckets)</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">race_clean =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(race) <span class="sc">~</span> <span class="st">"Missing"</span>,</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"^black$"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Black"</span>,</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"^white</span><span class="sc">\\</span><span class="st">b"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">&amp;</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>        <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"hispanic|latino"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"White (Hispanic/Latino)"</span>,</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"^white$"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"White"</span>,</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"hispanic|latino"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Hispanic/Latino"</span>,</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"asian"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Asian"</span>,</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"american</span><span class="sc">\\</span><span class="st">s*indian"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"American Indian"</span>,</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(race, <span class="fu">regex</span>(<span class="st">"unknown"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Missing"</span>,</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other/Unknown"</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Clean gender</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender_clean =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(gender) <span class="sc">~</span> <span class="st">"Missing"</span>,</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(gender, <span class="fu">regex</span>(<span class="st">"^male$"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Male"</span>,</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(gender, <span class="fu">regex</span>(<span class="st">"^female$"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Female"</span>,</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(gender, <span class="fu">regex</span>(<span class="st">"unknown"</span>, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)) <span class="sc">~</span> <span class="st">"Other/Unknown"</span>,</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other/Unknown"</span></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Judge: many categories -&gt; lump to avoid an enormous model</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>    <span class="at">judge_clean =</span> <span class="fu">fct_explicit_na</span>(<span class="fu">factor</span>(sentence_judge), <span class="at">na_level =</span> <span class="st">"Missing"</span>),</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>    <span class="at">judge_group =</span> <span class="fu">fct_lump_n</span>(judge_clean, <span class="at">n =</span> <span class="dv">25</span>, <span class="at">other_level =</span> <span class="st">"Other judges"</span>),</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Controls you already started using (lump levels to keep model stable)</span></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">offense_group =</span> <span class="fu">fct_lump_n</span>(<span class="fu">factor</span>(updated_offense_category), <span class="at">n =</span> <span class="dv">15</span>, <span class="at">other_level =</span> <span class="st">"Other offenses"</span>),</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">disp_class_group =</span> <span class="fu">fct_lump_n</span>(<span class="fu">factor</span>(disposition_charged_class), <span class="at">n =</span> <span class="dv">10</span>, <span class="at">other_level =</span> <span class="st">"Other/Unknown"</span>),</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">sentence_type =</span> <span class="fu">fct_explicit_na</span>(<span class="fu">factor</span>(sentence_type), <span class="at">na_level =</span> <span class="st">"Missing"</span>),</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Time: sentencing year can matter (policy/guideline changes over time)</span></span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">sentence_date_parsed =</span> <span class="fu">parse_date_time</span>(<span class="fu">as.character</span>(sentence_date), <span class="at">orders =</span> <span class="st">"Y b d I:M:S p"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>),</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">sentencing_year =</span> <span class="fu">factor</span>(<span class="fu">year</span>(sentence_date_parsed)),</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">sentencing_year_num =</span> <span class="fu">year</span>(sentence_date_parsed),</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Modeling convenience: log transform for skew</span></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>    <span class="at">log_years =</span> <span class="fu">log1p</span>(years_sentenced)</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep rows where key analysis variables exist</span></span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(years_sentenced),</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>    years_sentenced <span class="sc">&gt;=</span> <span class="dv">0</span>,</span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>    years_sentenced <span class="sc">&lt;=</span> <span class="dv">200</span>,              <span class="co"># trims extreme likely entry issues; still allows very long sentences</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(age_at_incident),</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(charge_count),</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(length_of_case_in_days),</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(offense_group),</span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(disp_class_group),</span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(sentence_type)</span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>    <span class="co"># reference categories for interpretability</span></span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a>    <span class="at">race_clean =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(race_clean), <span class="st">"White"</span>),</span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender_clean =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(gender_clean), <span class="st">"Male"</span>),</span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">sentence_type =</span> <span class="fu">fct_relevel</span>(sentence_type, <span class="st">"Probation"</span>)</span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a>sent_clean <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       n
   &lt;int&gt;
1 190217</code></pre>
</div>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer generates HTML, results = 'asis' to render properly</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1(c): Descriptive statistics table (key numeric variables)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>desc_df <span class="ot">&lt;-</span> sent_clean <span class="sc">|&gt;</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    years_sentenced,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    age_at_incident,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    charge_count,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    length_of_case_in_days</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(desc_df),</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"html"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Descriptive Statistics (Key Numeric Variables)"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<table style="text-align:center">
<caption>
<strong>Descriptive Statistics (Key Numeric Variables)</strong>
</caption>
<tbody><tr>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St.&nbsp;Dev.
</td>
<td>
Min
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
years_sentenced
</td>
<td>
190,217
</td>
<td>
2.89
</td>
<td>
3.73
</td>
<td>
0.00
</td>
<td>
189.00
</td>
</tr>
<tr>
<td style="text-align:left">
age_at_incident
</td>
<td>
190,217
</td>
<td>
32.92
</td>
<td>
11.88
</td>
<td>
17
</td>
<td>
137
</td>
</tr>
<tr>
<td style="text-align:left">
charge_count
</td>
<td>
190,217
</td>
<td>
1.06
</td>
<td>
0.71
</td>
<td>
1
</td>
<td>
61
</td>
</tr>
<tr>
<td style="text-align:left">
length_of_case_in_days
</td>
<td>
190,217
</td>
<td>
291.07
</td>
<td>
2,138.42
</td>
<td>
-328,549
</td>
<td>
329,379
</td>
</tr>
<tr>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
</tbody></table>
<p><strong>Q1(c) What stands out / what variables look interesting?</strong></p>
<p>Of the continuious variables, the average sentence length is about 2.89 years, with a wide range from 0 to 189 years (after cleaning). The average age at incident is around 33 years old. The average charge count is about 1 charges per case, and the average length of case in days is 291 days.</p>
<p>What stands out to me most is the average length of case in days count. It seems quite high to me, as I would have expected most cases to be resolved within a few months. This suggests that there may be a significant number of cases that take much longer to resolve, potentially due to complexities in the legal process or delays in court proceedings. Additionally, its standard deviations is at 2,138 days, which indicates a wide variability in case lengths. This variability could be an interesting area for further exploration, as it may reveal insights into the factors that contribute to longer or shorter case durations.</p>
</section>
<section id="d-is-there-reason-to-believe-you-have-a-good-research-question-t-test" class="level2">
<h2 class="anchored" data-anchor-id="d-is-there-reason-to-believe-you-have-a-good-research-question-t-test">1(d) Is there reason to believe you have a good research question? (t-test)</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1(d): t-test (simple evidence of group differences)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> sent_clean <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(race_clean <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Black"</span>,<span class="st">"White"</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(log_years <span class="sc">~</span> race_clean, <span class="at">data =</span> bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  log_years by race_clean
t = -18.18, df = 42716, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group White and group Black is not equal to 0
95 percent confidence interval:
 -0.06512863 -0.05245231
sample estimates:
mean in group White mean in group Black 
           1.137761            1.196552 </code></pre>
</div>
</div>
<p>This T-test is solely motivational, as the research question focuses on the overall modeling of sentence length, but this t test provides preliminary evidence that there are indeed differences in sentencing outcomes by race, one of the key demographic variables of interest in the research question.</p>
<p><strong>Q1(d) Interpretation:</strong><br>
The two-sample t-test comparing mean log sentence length between Black and White defendants shows a highly statistically significant difference (t = −18.18, p &lt; 2.2e−16). The null hypothesis of equal means is therefore decisively rejected. The estimated 95% confidence interval for the difference in mean log sentence length (White − Black) is [−0.065, −0.052], which does not include zero.</p>
<p>The sample means indicate that Black defendants have a higher average log sentence length (mean = 1.196) than White defendants (mean = 1.138). This unadjusted difference suggests a meaningful disparity in sentencing outcomes by race in the raw data.</p>
<p>While this result is purely descriptive and not prepared to extraploate, it provides strong motivation for a more careful modeling approach that controls for legally relevant factors such as offense type, charge class, sentence type, and judge. The presence of a large and statistically precise difference at this preliminary stage supports the validity of the research question and suggests that race, alongside judicial assignment and case characteristics, may play an important role in predicting sentence length.</p>
</section>
<section id="e-other-relevant-descriptive-statistics-plots" class="level2">
<h2 class="anchored" data-anchor-id="e-other-relevant-descriptive-statistics-plots">1(e) Other relevant descriptive statistics (plots)</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1(e): Visual descriptives</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution (trim for readability)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sent_clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(years_sentenced <span class="sc">&lt;=</span> <span class="dv">50</span>), <span class="fu">aes</span>(<span class="at">x =</span> years_sentenced)) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">60</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>,) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Sentence Length (Years) (visual trimmed at 50 years)"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Years sentenced"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/q1e-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># By race</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sent_clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(years_sentenced <span class="sc">&lt;=</span> <span class="dv">50</span>), <span class="fu">aes</span>(<span class="at">x =</span> race_clean, <span class="at">y =</span> years_sentenced)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"lightsteelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Sentence Length by Race (Years) (visual trimmed at 50 years)"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Race"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Years sentenced"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/q1e-plots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># By gender</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sent_clean <span class="sc">|&gt;</span> <span class="fu">filter</span>(years_sentenced <span class="sc">&lt;=</span> <span class="dv">50</span>), <span class="fu">aes</span>(<span class="at">x =</span> gender_clean, <span class="at">y =</span> years_sentenced)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">"navajowhite"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Sentence Length by Gender (Years) (visual trimmed at 50 years)"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Gender"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Years sentenced"</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/q1e-plots-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Judge summary (top 15 by volume, excluding "Other judges")</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>judge_summary <span class="ot">&lt;-</span> sent_clean <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(judge_group) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_years =</span> <span class="fu">mean</span>(years_sentenced, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_years =</span> <span class="fu">median</span>(years_sentenced, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>judge_summary <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">15</span>) <span class="sc">|&gt;</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">judge_group</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean_years</th>
<th style="text-align: right;">median_years</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Other judges</td>
<td style="text-align: right;">115151</td>
<td style="text-align: right;">2.825148</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Charles P Burns</td>
<td style="text-align: right;">3735</td>
<td style="text-align: right;">3.117640</td>
<td style="text-align: right;">2.001534</td>
</tr>
<tr class="odd">
<td style="text-align: left;">James B Linn</td>
<td style="text-align: right;">3680</td>
<td style="text-align: right;">3.505860</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nicholas R Ford</td>
<td style="text-align: right;">3630</td>
<td style="text-align: right;">3.392475</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lawrence Edward Flood</td>
<td style="text-align: right;">3451</td>
<td style="text-align: right;">2.914942</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">James Michael Obbish</td>
<td style="text-align: right;">3450</td>
<td style="text-align: right;">3.374324</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colleen Ann Hyland</td>
<td style="text-align: right;">3399</td>
<td style="text-align: right;">2.531815</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Carol M Howard</td>
<td style="text-align: right;">3374</td>
<td style="text-align: right;">2.899171</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">William T O’Brien</td>
<td style="text-align: right;">3364</td>
<td style="text-align: right;">3.135617</td>
<td style="text-align: right;">2.501918</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenneth J Wadas</td>
<td style="text-align: right;">3206</td>
<td style="text-align: right;">2.997022</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stanley Sacks</td>
<td style="text-align: right;">3147</td>
<td style="text-align: right;">3.569609</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geary W Kull</td>
<td style="text-align: right;">3114</td>
<td style="text-align: right;">2.272309</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mary Margaret Brosnahan</td>
<td style="text-align: right;">3022</td>
<td style="text-align: right;">2.992368</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thaddeus L Wilson</td>
<td style="text-align: right;">2923</td>
<td style="text-align: right;">3.367199</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brian K Flaherty</td>
<td style="text-align: right;">2850</td>
<td style="text-align: right;">3.371540</td>
<td style="text-align: right;">2.000000</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(judge_summary <span class="sc">|&gt;</span> <span class="fu">filter</span>(judge_group <span class="sc">!=</span> <span class="st">"Other judges"</span>) <span class="sc">|&gt;</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">15</span>),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(judge_group, mean_years), <span class="at">y =</span> mean_years)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"forestgreen"</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Sentence Length by Judge Group (Top 15 by volume)"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Judge group"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean years sentenced"</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/q1e-plots-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="hypothesis" class="level1">
<h1>2. Hypothesis</h1>
<section id="a-hypothesis-and-expected-trend" class="level2">
<h2 class="anchored" data-anchor-id="a-hypothesis-and-expected-trend">2(a) Hypothesis and expected trend</h2>
<p><strong>Null (H0):</strong><br>
After accounting for legally relevant case characteristics and the inclusion of judge identity as a predictor, sentence length is fully explained by observable case factors, and defendant race and gender have no additional association with years sentenced.</p>
<p><strong>Hypothesis (H1):</strong><br>
Even after accounting for legally relevant case characteristics and including judge identity as a predictor, sentence length is not fully explained by case factors alone, and defendant race and gender remain systematically associated with years sentenced.</p>
<p><strong>Expected trends (why):</strong><br>
- Judge identity is incorporated by including judge-group indicator variables, where the most frequent judges are kept as their own categories and low-volume judges are pooled into an “Other judges” group to keep the model stable and interpretable.</p>
<ul>
<li>Race/gender differences could appear due to a mix of case selection into categories not fully observed (priors, plea decisions, guideline departures) and/or differential treatment—this project is descriptive/predictive, not causal.</li>
</ul>
</section>
<section id="b-model-specification-why-this-trend" class="level2">
<h2 class="anchored" data-anchor-id="b-model-specification-why-this-trend">2(b) Model Specification, why this trend?</h2>
<p>I model sentence length in years on a log scale:</p>
<p><span class="math display">\[
\log(1+\text{years}) = \beta_0 + \beta_1(\text{race}) + \beta_2(\text{gender}) + \beta_3(\text{judge}) + \beta X + \varepsilon
\]</span> – This formula visualization is generated by AI.</p>
<p>The primary explanatory variables of interest are judge identity, defendant race, and defendant gender, as these factors capture both institutional discretion and demographic characteristics that prior research and public discussion suggest may be associated with sentencing outcomes. The model also includes legally relevant control variables—offense category, charged offense class, sentence type, number of charges, defendant age at the incident, and length of the case—which are expected to systematically influence sentence severity based on statutory guidelines and case complexity. In some specifications, year fixed effects are included to account for changes in sentencing practices over time due to policy shifts, judicial turnover, or evolving prosecutorial norms.</p>
<p>This functional form is chosen for two main reasons. First, sentence length is highly right-skewed, with a small number of extremely long sentences. Taking the logarithm reduces the influence of these extreme values and helps stabilize the variance of the error term, improving model fit and interpretability. Second, the log specification allows coefficients to be interpreted as approximate percentage differences in sentence length, which is intuitive when comparing outcomes across demographic groups or judges, particularly when baseline sentence lengths vary substantially across cases.</p>
<p>The inclusion of judge fixed effects is motivated by descriptive evidence of substantial variation in average sentence length across judges, suggesting that judicial assignment may meaningfully shape sentencing outcomes beyond case characteristics alone. This variation reflects differences in judicial philosophy, experience, and sentencing discretion, making judge identity a central predictor in a model of sentence length. The inclusion of demographic variables such as race and gender allows the model to test whether observable differences in sentencing persist after conditioning on legally relevant case factors. Overall, the model is designed to capture systematic trends in sentencing outcomes while separating the roles of institutional discretion, case characteristics, and defendant demographics.</p>
</section>
<section id="c-what-would-make-you-rejectrespecify" class="level2">
<h2 class="anchored" data-anchor-id="c-what-would-make-you-rejectrespecify">2(c) What would make you reject/respecify?</h2>
<p>I would respecify if: - diagnostics show extreme heteroskedasticity or nonlinearity even on the log scale, - judge categories are too sparse (overfitting); I address this by lumping judges, - out-of-sample error is poor, suggesting missing key predictors or that a different functional form (e.g., Gamma regression) is needed.</p>
<hr>
</section>
</section>
<section id="regression" class="level1">
<h1>3. Regression</h1>
<section id="a-run-regressions-and-iterate-to-find-the-best-performer" class="level2">
<h2 class="anchored" data-anchor-id="a-run-regressions-and-iterate-to-find-the-best-performer">3(a) Run regressions and iterate to find the best performer</h2>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q3(a): Use the full cleaned sample </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sent_clean)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>sent_clean <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
       n
   &lt;int&gt;
1 190217</code></pre>
</div>
</div>
<p>Candidate models (predictive)</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcome = log_years</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Model 0: baseline mean-only</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_years <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> sent_clean)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Model 1: demographics (+ age)</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_years <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident, <span class="at">data =</span> sent_clean)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: add legal/case controls (strong predictors)</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    log_years <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>      charge_count <span class="sc">+</span> length_of_case_in_days <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>      offense_group <span class="sc">+</span> disp_class_group <span class="sc">+</span> sentence_type,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sent_clean</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: add judge (key variable requested)</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    log_years <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident <span class="sc">+</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>      charge_count <span class="sc">+</span> length_of_case_in_days <span class="sc">+</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>      offense_group <span class="sc">+</span> disp_class_group <span class="sc">+</span> sentence_type <span class="sc">+</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>      judge_group,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sent_clean</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 4: add year fixed effects (captures time/policy shifts)</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>  m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    log_years <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident <span class="sc">+</span></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>      charge_count <span class="sc">+</span> length_of_case_in_days <span class="sc">+</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>      offense_group <span class="sc">+</span> disp_class_group <span class="sc">+</span> sentence_type <span class="sc">+</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>      judge_group <span class="sc">+</span> sentencing_year_num,</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sent_clean</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a><span class="co"># function to compute performance on original YEARS scale</span></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>eval_on_years <span class="ot">&lt;-</span> <span class="cf">function</span>(model, data_df) {</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>  pred_log <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> data_df)</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>  pred_years <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="dv">0</span>, <span class="fu">expm1</span>(pred_log))  <span class="co"># back-transform; enforce nonnegative</span></span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">rmse_years =</span> <span class="fu">rmse</span>(data_df<span class="sc">$</span>years_sentenced, pred_years),</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">mae_years  =</span> <span class="fu">mae</span>(data_df<span class="sc">$</span>years_sentenced, pred_years)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>perf <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">model =</span> <span class="st">"m0: mean only"</span>,      <span class="fu">eval_on_years</span>(m0, sent_clean)),</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">model =</span> <span class="st">"m1: demo + age"</span>,     <span class="fu">eval_on_years</span>(m1, sent_clean)),</span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">model =</span> <span class="st">"m2: + case controls"</span>,<span class="fu">eval_on_years</span>(m2, sent_clean)),</span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">model =</span> <span class="st">"m3: + judge"</span>,        <span class="fu">eval_on_years</span>(m3, sent_clean)),</span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">model =</span> <span class="st">"m4: + judge + year"</span>, <span class="fu">eval_on_years</span>(m4, sent_clean))</span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">adj_r2 =</span> <span class="fu">c</span>(<span class="fu">summary</span>(m0)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(m1)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(m2)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(m3)<span class="sc">$</span>adj.r.squared,</span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summary</span>(m4)<span class="sc">$</span>adj.r.squared))</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a>perf <span class="sc">|&gt;</span> <span class="fu">arrange</span>(rmse_years) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">rmse_years</th>
<th style="text-align: right;">mae_years</th>
<th style="text-align: right;">adj_r2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">m4: + judge + year</td>
<td style="text-align: right;">2.5233</td>
<td style="text-align: right;">1.0483</td>
<td style="text-align: right;">0.6311</td>
</tr>
<tr class="even">
<td style="text-align: left;">m3: + judge</td>
<td style="text-align: right;">2.5269</td>
<td style="text-align: right;">1.0491</td>
<td style="text-align: right;">0.6305</td>
</tr>
<tr class="odd">
<td style="text-align: left;">m2: + case controls</td>
<td style="text-align: right;">2.5302</td>
<td style="text-align: right;">1.0520</td>
<td style="text-align: right;">0.6286</td>
</tr>
<tr class="even">
<td style="text-align: left;">m1: demo + age</td>
<td style="text-align: right;">3.7707</td>
<td style="text-align: right;">1.5463</td>
<td style="text-align: right;">0.0139</td>
</tr>
<tr class="odd">
<td style="text-align: left;">m0: mean only</td>
<td style="text-align: right;">3.7859</td>
<td style="text-align: right;">1.5506</td>
<td style="text-align: right;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Regression table</p>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  m1, m2, m3, m4,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"html"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Models Predicting log(1 + years sentenced)"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit =</span> <span class="fu">c</span>(<span class="st">"offense_group"</span>, <span class="st">"disp_class_group"</span>, <span class="st">"sentence_type"</span>, <span class="st">"judge_group"</span>, <span class="st">"sentencing_year"</span>),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit.stat =</span> <span class="fu">c</span>(<span class="st">"f"</span>, <span class="st">"ser"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<table style="text-align:center">
<caption>
<strong>Models Predicting log(1 + years sentenced)</strong>
</caption>
<tbody><tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="4">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="4">
log_years
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanAmerican Indian
</td>
<td>
0.147<sup>***</sup>
</td>
<td>
0.017
</td>
<td>
0.017
</td>
<td>
0.017
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.054)
</td>
<td>
(0.033)
</td>
<td>
(0.033)
</td>
<td>
(0.033)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanAsian
</td>
<td>
-0.028<sup>*</sup>
</td>
<td>
-0.025<sup>***</sup>
</td>
<td>
-0.026<sup>***</sup>
</td>
<td>
-0.025<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.015)
</td>
<td>
(0.009)
</td>
<td>
(0.009)
</td>
<td>
(0.009)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanBlack
</td>
<td>
0.044<sup>***</sup>
</td>
<td>
0.010<sup>***</sup>
</td>
<td>
0.007<sup>***</sup>
</td>
<td>
0.008<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
<td>
(0.002)
</td>
<td>
(0.002)
</td>
<td>
(0.002)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanHispanic/Latino
</td>
<td>
-0.081<sup>***</sup>
</td>
<td>
0.018<sup>***</sup>
</td>
<td>
0.020<sup>***</sup>
</td>
<td>
0.016<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.010)
</td>
<td>
(0.006)
</td>
<td>
(0.006)
</td>
<td>
(0.006)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanMissing
</td>
<td>
-0.079<sup>***</sup>
</td>
<td>
-0.001
</td>
<td>
0.001
</td>
<td>
0.003
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.019)
</td>
<td>
(0.012)
</td>
<td>
(0.012)
</td>
<td>
(0.012)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanOther/Unknown
</td>
<td>
-0.190<sup>**</sup>
</td>
<td>
-0.051
</td>
<td>
-0.050
</td>
<td>
-0.045
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.085)
</td>
<td>
(0.052)
</td>
<td>
(0.052)
</td>
<td>
(0.052)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
race_cleanWhite (Hispanic/Latino)
</td>
<td>
0.012<sup>***</sup>
</td>
<td>
0.012<sup>***</sup>
</td>
<td>
0.009<sup>***</sup>
</td>
<td>
0.011<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
<td>
(0.003)
</td>
<td>
(0.003)
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
gender_cleanFemale
</td>
<td>
-0.143<sup>***</sup>
</td>
<td>
-0.027<sup>***</sup>
</td>
<td>
-0.027<sup>***</sup>
</td>
<td>
-0.028<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
<td>
(0.002)
</td>
<td>
(0.002)
</td>
<td>
(0.002)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
gender_cleanMissing
</td>
<td>
-0.073<sup>**</sup>
</td>
<td>
-0.016
</td>
<td>
-0.015
</td>
<td>
-0.020
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.030)
</td>
<td>
(0.018)
</td>
<td>
(0.018)
</td>
<td>
(0.018)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
gender_cleanOther/Unknown
</td>
<td>
0.070
</td>
<td>
-0.073
</td>
<td>
-0.073
</td>
<td>
-0.064
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.106)
</td>
<td>
(0.065)
</td>
<td>
(0.065)
</td>
<td>
(0.065)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
age_at_incident
</td>
<td>
-0.002<sup>***</sup>
</td>
<td>
0.002<sup>***</sup>
</td>
<td>
0.002<sup>***</sup>
</td>
<td>
0.002<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
charge_count
</td>
<td>
</td>
<td>
-0.0004
</td>
<td>
-0.0004
</td>
<td>
-0.001
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.001)
</td>
<td>
(0.001)
</td>
<td>
(0.001)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
length_of_case_in_days
</td>
<td>
</td>
<td>
0.00000<sup>***</sup>
</td>
<td>
0.00000<sup>***</sup>
</td>
<td>
0.00001<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.00000)
</td>
<td>
(0.00000)
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
1.245<sup>***</sup>
</td>
<td>
1.515<sup>***</sup>
</td>
<td>
1.521<sup>***</sup>
</td>
<td>
8.449<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.005)
</td>
<td>
(0.007)
</td>
<td>
(0.010)
</td>
<td>
(0.380)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
190,217
</td>
<td>
190,217
</td>
<td>
190,217
</td>
<td>
190,217
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.014
</td>
<td>
0.629
</td>
<td>
0.631
</td>
<td>
0.631
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.014
</td>
<td>
0.629
</td>
<td>
0.630
</td>
<td>
0.631
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="4" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted vs actual for the best model (4)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>best_model_name <span class="ot">&lt;-</span> perf <span class="sc">|&gt;</span> <span class="fu">arrange</span>(rmse_years) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(model)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">&lt;-</span> <span class="cf">switch</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  best_model_name,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"m0: mean only"</span> <span class="ot">=</span> m0,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"m1: demo + age"</span> <span class="ot">=</span> m1,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"m2: + case controls"</span> <span class="ot">=</span> m2,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"m3: + judge"</span> <span class="ot">=</span> m3,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"m4: + judge + year"</span> <span class="ot">=</span> m4</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># In-sample predictions on `sent_clean`</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>sent_pred_years <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="dv">0</span>, <span class="fu">expm1</span>(<span class="fu">predict</span>(best_model, <span class="at">newdata =</span> sent_clean)))</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> sent_clean <span class="sc">|&gt;</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_years =</span> sent_pred_years) <span class="sc">|&gt;</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(years_sentenced, pred_years)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="fu">min</span>(<span class="dv">8000</span>, <span class="fu">nrow</span>(plot_df))), <span class="fu">aes</span>(<span class="at">x =</span> years_sentenced, <span class="at">y =</span> pred_years)) <span class="sc">+</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Predicted vs Actual Sentence Length ("</span>, best_model_name, <span class="st">")"</span>),</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Actual years sentenced"</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted years sentenced"</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">30</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the pred vs.&nbsp;actual plot for model 4, there is an obvious distinction between two groups. I beleive it to be because of mandiatory minimums and maximums for certain offenses that cause clustering of sentences at specific lengths. For example, drug offenses may have mandatory minimum sentences that lead to a concentration of sentences at those lengths, while other offenses may have statutory maximums that cap the length of sentences. This results in a non-linear relationship between predicted and actual sentence lengths, as the model may not fully capture these legal constraints.</p>
<p>Nonetheless, I thought it would be a great opportunity to run k-means clustering, to test its effectiveness in identifying these two regimes in the data, as a way to further explore the model’s performance across different sentence length categories.</p>
<section id="clustering" class="level3">
<h3 class="anchored" data-anchor-id="clustering">Clustering</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add clustering to the prediction data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">91</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>cluster_df <span class="ot">&lt;-</span> plot_df <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">actual_scaled =</span> <span class="fu">scale</span>(years_sentenced),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_scaled   =</span> <span class="fu">scale</span>(pred_years)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose number of clusters (k = 4 is intuitive here)</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>km <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(cluster_df <span class="sc">|&gt;</span> <span class="fu">select</span>(actual_scaled, pred_scaled), <span class="at">centers =</span> k)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>cluster_df <span class="ot">&lt;-</span> cluster_df <span class="sc">|&gt;</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cluster =</span> <span class="fu">factor</span>(km<span class="sc">$</span>cluster))</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot </span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  cluster_df <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="fu">min</span>(<span class="dv">8000</span>, <span class="fu">nrow</span>(cluster_df))),</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> years_sentenced, <span class="at">y =</span> pred_years, <span class="at">color =</span> cluster)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Predicted vs Actual Sentence Length with Clusters ("</span>, best_model_name, <span class="st">")"</span>),</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Actual years sentenced"</span>,</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted years sentenced"</span>,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Cluster"</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">30</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="b-evaluate" class="level2">
<h2 class="anchored" data-anchor-id="b-evaluate">3(b) Evaluate</h2>
<section id="bi-which-model-performs-best-why" class="level3">
<h3 class="anchored" data-anchor-id="bi-which-model-performs-best-why">3(b)(i) Which model performs best? Why?</h3>
<p>Model 4, which includes legally relevant case characteristics, judge identity, and a time trend, performs best according to all evaluation metrics. It achieves the lowest RMSE (2.52 years) and lowest MAE (1.05 years) among the candidate models, indicating the most accurate predictions of sentence length on average. Model 4 also has the highest adjusted R-square (0.631), explaining slightly more variation in sentence length than models that exclude judge or time controls. Although the performance gains over Model 3 are modest, they suggest that accounting for both judicial heterogeneity and temporal variation provides incremental improvements in predictive performance beyond case characteristics alone.</p>
<p>Model 4 performs best primarily because it includes the most information, incorporating legally relevant case characteristics, judge identity, and a time trend. By construction, adding additional predictors to a linear regression model cannot decrease R-sqare and will typically improve in-sample fit, even if the added variables have limited substantive importance. For this reason, the improvement in R-square alone should not be interpreted as strong evidence that the added variables are crucial drivers of sentencing outcomes.</p>
</section>
<section id="bii-do-you-trust-your-model-why" class="level3">
<h3 class="anchored" data-anchor-id="bii-do-you-trust-your-model-why">3(b)(ii) Do you trust your model? Why?</h3>
<p>I trust the model more as a predictive and descriptive tool than as a causal explanation of sentencing outcomes. It performs well in terms of fit and prediction accuracy, explaining about 63 percent of the variation in log sentence length, and the stability of coefficients across specifications suggests that the results are not driven by simple omitted variable bias from offense type alone. However, several important determinants of sentencing, such as prior criminal history, plea bargaining, sentencing guideline ranges, and quality of legal representation, are not observed in the data and cannot be fully captured by categorical controls. As a result, the estimated race and gender coefficients should be interpreted as conditional associations rather than causal effects.</p>
</section>
<section id="biii-publication-ready-what-would-you-need" class="level3">
<h3 class="anchored" data-anchor-id="biii-publication-ready-what-would-you-need">3(b)(iii) Publication-ready? What would you need?</h3>
<p>Not yet. To get closer to publication quality, the analysis would need to incorporate additional key controls such as criminal history, plea versus trial status, and sentencing guideline ranges. It would also benefit from robustness checks using alternative samples, such as restricting to felony cases or specific offense categories. In addition, stronger identification strategies, including approaches that rely on plausibly random judge assignment, would be necessary to support causal interpretation. Finally, fairness focused evaluations, such as comparing prediction errors and calibration across demographic groups, would help assess whether the model performs equitably across populations.</p>
<hr>
</section>
</section>
</section>
<section id="tests" class="level1">
<h1>4. Tests</h1>
<section id="a-what-tests-do-we-need" class="level2">
<h2 class="anchored" data-anchor-id="a-what-tests-do-we-need">4(a) What tests do we need?</h2>
<p>For linear regression, common checks include: - ANOVA / nested F-test (e.g., does adding judge improve fit?),</p>
<ul>
<li><p>Residuals vs fitted (nonlinearity / heteroskedasticity),</p></li>
<li><p>QQ plot (normality of residuals),</p></li>
<li><p>Corrplot of numeric predictors (multicollinearity concerns),</p></li>
<li><p>Breusch–Pagan test (heteroskedasticity).</p></li>
</ul>
</section>
<section id="b-run-them-does-the-model-pass" class="level2">
<h2 class="anchored" data-anchor-id="b-run-them-does-the-model-pass">4(b) Run them + does the model pass?</h2>
<section id="corrplot" class="level3">
<h3 class="anchored" data-anchor-id="corrplot">Corrplot</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation among key numeric predictors</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>num_df <span class="ot">&lt;-</span> sent_clean <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    years_sentenced,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    log_years,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    age_at_incident,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    charge_count,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    length_of_case_in_days</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>cor_mat <span class="ot">&lt;-</span> <span class="fu">cor</span>(num_df)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(cor_mat, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">tl.cex =</span> <span class="fl">0.8</span>, <span class="at">addCoef.col =</span> <span class="st">"black"</span>, <span class="at">number.cex =</span> <span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/q1e-corrplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation matrix shows no evidence of problematic multicollinearity among the predictors. Aside from the expected high correlation between years_sentenced and log_years, all other correlations are close to zero. This indicates that the model passes the multicollinearity check.</p>
</section>
<section id="qq-plot" class="level3">
<h3 class="anchored" data-anchor-id="qq-plot">QQ plot</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(m4), <span class="at">main =</span> <span class="st">"QQ Plot of Residuals (m4)"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(m4), <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The QQ plot shows that the residuals deviate from the reference line in the tails, particularly for large positive residuals, indicating heavier tails than a normal distribution. This suggests that while the residuals are approximately normal in the center, extreme sentencing outcomes are not well captured by the model. Given the large sample size, this deviation is not unexpected and does not invalidate the model, but it reinforces the use of robust standard errors and cautions against relying on normality assumptions for inference.</p>
</section>
<section id="heteroskedasticity-test" class="level3">
<h3 class="anchored" data-anchor-id="heteroskedasticity-test">Heteroskedasticity test</h3>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals plot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m4<span class="sc">$</span>fitted.values, <span class="fu">resid</span>(m4),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Fitted values"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuals vs Fitted (m4)"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="EconStatsFinal_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Additional method: This was covered in Foundations of Data Science (Pomona) </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(m4) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m4
BP = 10932, df = 77, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Residual plot: The residuals-versus-fitted plot shows clear evidence of heteroskedasticity, with the variance of residuals increasing at higher fitted values. This pattern is consistent with formal test results and reflects greater uncertainty in predicting long sentences. However, the absence of strong curvature suggests that the log-linear functional form is appropriate for modeling the conditional mean.</p>
<p>B-P Test (Learned in Foundations of Data Science): - The Breusch–Pagan test is a formal statistical test that examines whether the variance of the regression residuals is constant across observations, with a significant result indicating heteroskedasticity.</p>
<p>The studentized Breusch–Pagan test strongly rejects the null hypothesis of homoskedasticity (BP = 10,823, p &lt; 2.2e−16), indicating that the variance of the regression errors is not constant across observations. This confirms the presence of heteroskedasticity in the model, which is consistent with earlier diagnostics showing larger errors for long sentences. As a result, standard OLS standard errors may be unreliable, and the use of heteroskedasticity-robust standard errors is appropriate for inference.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q4(b): Does adding judge improve fit? (nested F-test)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare m2 (no judge) vs m3 (with judge)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2, m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log_years ~ race_clean + gender_clean + age_at_incident + charge_count + 
    length_of_case_in_days + offense_group + disp_class_group + 
    sentence_type
Model 2: log_years ~ race_clean + gender_clean + age_at_incident + charge_count + 
    length_of_case_in_days + offense_group + disp_class_group + 
    sentence_type + judge_group
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1 190165 19129                                  
2 190140 19031 25    97.878 39.116 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The nested F-test compares Model 2, which includes legally relevant case characteristics, to Model 3, which additionally includes judge identity as a set of predictors. The test strongly rejects the null hypothesis that the coefficients on the judge indicators are jointly equal to zero (F = 39.12, p &lt; 2.2e−16). This indicates that, taken together, judge identity explains a statistically significant amount of additional variation in log sentence length beyond offense type, charge class, sentence type, and other case characteristics.</p>
<p>Although the increase in overall model fit is modest in magnitude, the highly significant F-statistic reflects both the large sample size and the systematic differences in average sentencing severity across judges. Substantively, this result suggests that judicial assignment is meaningfully associated with sentencing outcomes, even after accounting for legally relevant case factors. However, this finding should be interpreted as descriptive rather than causal, as judge assignment is not assumed to be random and the test does not identify the sources of judicial variation.</p>
</section>
<section id="residual-analysis-for-zero-conditional-mean-assumption" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis-for-zero-conditional-mean-assumption">Residual Analysis for Zero Conditional Mean Assumption</h3>
<p>To test the Zero Conditional Mean (Exogeneity) assumption, we perform a residual analysis. This involves regressing the residuals from the main regression model on the independent variables. If the coefficients in this regression are statistically significant, it suggests that the residuals are correlated with the predictors, indicating a potential violation of the assumption.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the main regression model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>main_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_years <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                   charge_count <span class="sc">+</span> length_of_case_in_days <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                   offense_group <span class="sc">+</span> disp_class_group <span class="sc">+</span> sentence_type <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                   judge_group <span class="sc">+</span> sentencing_year_num, <span class="at">data =</span> sent_clean)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">resid</span>(main_model)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Regress residuals on independent variables</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>residual_test <span class="ot">&lt;-</span> <span class="fu">lm</span>(residuals <span class="sc">~</span> race_clean <span class="sc">+</span> gender_clean <span class="sc">+</span> age_at_incident <span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>                      charge_count <span class="sc">+</span> length_of_case_in_days <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>                      offense_group <span class="sc">+</span> disp_class_group <span class="sc">+</span> sentence_type <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                      judge_group <span class="sc">+</span> sentencing_year_num, <span class="at">data =</span> sent_clean)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the residual regression</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(residual_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = residuals ~ race_clean + gender_clean + age_at_incident + 
    charge_count + length_of_case_in_days + offense_group + disp_class_group + 
    sentence_type + judge_group + sentencing_year_num, data = sent_clean)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4630 -0.2223 -0.0175  0.1955  4.4978 

Coefficients:
                                                         Estimate Std. Error
(Intercept)                                             6.285e-15  3.795e-01
race_cleanAmerican Indian                               7.395e-14  3.320e-02
race_cleanAsian                                         6.277e-15  9.394e-03
race_cleanBlack                                        -6.732e-16  2.238e-03
race_cleanHispanic/Latino                               2.664e-15  6.255e-03
race_cleanMissing                                      -4.581e-15  1.188e-02
race_cleanOther/Unknown                                 6.092e-14  5.201e-02
race_cleanWhite (Hispanic/Latino)                      -9.009e-16  2.704e-03
gender_cleanFemale                                     -3.920e-15  2.292e-03
gender_cleanMissing                                     2.222e-14  1.809e-02
gender_cleanOther/Unknown                              -2.789e-14  6.454e-02
age_at_incident                                         5.056e-17  6.561e-05
charge_count                                           -8.613e-17  1.032e-03
length_of_case_in_days                                  1.266e-20  5.604e-07
offense_groupAggravated Battery Police Officer         -1.718e-16  7.148e-03
offense_groupAggravated DUI                            -2.527e-16  6.473e-03
offense_groupArmed Robbery                             -1.009e-16  8.101e-03
offense_groupBurglary                                  -3.154e-16  6.621e-03
offense_groupDriving With Suspended Or Revoked License -3.251e-16  6.844e-03
offense_groupNarcotics                                 -1.701e-16  6.085e-03
offense_groupOther Offense                             -1.367e-16  8.113e-03
offense_groupPossession of Stolen Motor Vehicle         2.914e-16  7.510e-03
offense_groupPROMIS Conversion                         -6.353e-16  1.102e-02
offense_groupResidential Burglary                      -2.168e-16  7.459e-03
offense_groupRetail Theft                              -2.234e-16  6.428e-03
offense_groupRobbery                                   -2.478e-16  7.817e-03
offense_groupTheft                                     -4.428e-16  7.003e-03
offense_groupUUW - Unlawful Use of Weapon              -5.725e-16  6.225e-03
offense_groupOther offenses                             6.276e-17  6.011e-03
disp_class_group2                                      -6.021e-17  3.337e-03
disp_class_group3                                      -3.004e-17  3.493e-03
disp_class_group4                                      -2.480e-17  3.079e-03
disp_class_groupA                                      -3.332e-16  4.165e-03
disp_class_groupB                                      -4.363e-16  1.316e-02
disp_class_groupC                                      -1.614e-15  1.514e-02
disp_class_groupM                                      -1.175e-15  1.318e-02
disp_class_groupX                                      -4.450e-16  4.868e-03
disp_class_groupZ                                       5.395e-15  5.137e-02
disp_class_groupOther/Unknown                          -6.707e-16  5.690e-02
sentence_type2nd Chance Probation                      -1.233e-16  6.442e-03
sentence_typeConditional Discharge                     -1.580e-16  6.833e-03
sentence_typeConditional Release                       -2.299e-15  3.107e-02
sentence_typeConversion                                -1.172e-14  9.577e-02
sentence_typeCook County Boot Camp                     -7.149e-16  2.052e-02
sentence_typeDeath                                      6.386e-15  4.663e-02
sentence_typeInpatient Mental Health Services          -4.502e-16  4.229e-02
sentence_typeJail                                      -1.509e-16  4.011e-03
sentence_typePrison                                    -2.078e-16  1.676e-03
sentence_typeProbation Terminated Instanter             2.110e-15  4.265e-02
sentence_typeProbation Terminated Satisfactorily       -9.146e-16  7.073e-02
sentence_typeProbation Terminated Unsatisfactorily     -2.341e-15  2.387e-02
sentence_typeSupervision                                2.017e-15  6.765e-03
judge_groupBrian K Flaherty                            -2.017e-16  8.680e-03
judge_groupCarol M Howard                              -1.122e-16  8.340e-03
judge_groupCatherine Marie Haberkorn                    1.255e-16  8.914e-03
judge_groupCharles P Burns                              8.507e-16  8.169e-03
judge_groupColleen Ann Hyland                          -5.294e-17  8.383e-03
judge_groupGeary W Kull                                 4.348e-16  8.610e-03
judge_groupJames B Linn                                 9.707e-17  8.190e-03
judge_groupJames Michael Obbish                         1.103e-16  8.300e-03
judge_groupJoseph  Cataldo                             -1.469e-16  9.305e-03
judge_groupJoseph Michael Claps                        -1.239e-17  8.742e-03
judge_groupKenneth J Wadas                             -1.437e-17  8.430e-03
judge_groupLauren Gottainer Edidin                      9.649e-16  8.784e-03
judge_groupLawrence Edward Flood                       -3.811e-16  8.298e-03
judge_groupMary Margaret Brosnahan                     -1.950e-16  8.544e-03
judge_groupMichele M Pitman                            -1.851e-16  8.753e-03
judge_groupNeera  Walsh                                -2.489e-17  9.063e-03
judge_groupNicholas R Ford                             -1.836e-16  8.212e-03
judge_groupShelley  Sutker-Dermer                      -1.904e-16  8.890e-03
judge_groupStanley  Sacks                              -3.906e-16  8.466e-03
judge_groupThaddeus L Wilson                            1.028e-15  8.609e-03
judge_groupThomas J Hennelly                           -2.105e-16  8.751e-03
judge_groupVincent M Gaughan                           -1.080e-16  8.700e-03
judge_groupWilliam H Hooks                              1.192e-16  8.785e-03
judge_groupWilliam T O'Brien                            6.608e-16  8.372e-03
judge_groupOther judges                                -6.741e-17  6.390e-03
sentencing_year_num                                    -3.213e-18  1.884e-04
                                                       t value Pr(&gt;|t|)
(Intercept)                                                  0        1
race_cleanAmerican Indian                                    0        1
race_cleanAsian                                              0        1
race_cleanBlack                                              0        1
race_cleanHispanic/Latino                                    0        1
race_cleanMissing                                            0        1
race_cleanOther/Unknown                                      0        1
race_cleanWhite (Hispanic/Latino)                            0        1
gender_cleanFemale                                           0        1
gender_cleanMissing                                          0        1
gender_cleanOther/Unknown                                    0        1
age_at_incident                                              0        1
charge_count                                                 0        1
length_of_case_in_days                                       0        1
offense_groupAggravated Battery Police Officer               0        1
offense_groupAggravated DUI                                  0        1
offense_groupArmed Robbery                                   0        1
offense_groupBurglary                                        0        1
offense_groupDriving With Suspended Or Revoked License       0        1
offense_groupNarcotics                                       0        1
offense_groupOther Offense                                   0        1
offense_groupPossession of Stolen Motor Vehicle              0        1
offense_groupPROMIS Conversion                               0        1
offense_groupResidential Burglary                            0        1
offense_groupRetail Theft                                    0        1
offense_groupRobbery                                         0        1
offense_groupTheft                                           0        1
offense_groupUUW - Unlawful Use of Weapon                    0        1
offense_groupOther offenses                                  0        1
disp_class_group2                                            0        1
disp_class_group3                                            0        1
disp_class_group4                                            0        1
disp_class_groupA                                            0        1
disp_class_groupB                                            0        1
disp_class_groupC                                            0        1
disp_class_groupM                                            0        1
disp_class_groupX                                            0        1
disp_class_groupZ                                            0        1
disp_class_groupOther/Unknown                                0        1
sentence_type2nd Chance Probation                            0        1
sentence_typeConditional Discharge                           0        1
sentence_typeConditional Release                             0        1
sentence_typeConversion                                      0        1
sentence_typeCook County Boot Camp                           0        1
sentence_typeDeath                                           0        1
sentence_typeInpatient Mental Health Services                0        1
sentence_typeJail                                            0        1
sentence_typePrison                                          0        1
sentence_typeProbation Terminated Instanter                  0        1
sentence_typeProbation Terminated Satisfactorily             0        1
sentence_typeProbation Terminated Unsatisfactorily           0        1
sentence_typeSupervision                                     0        1
judge_groupBrian K Flaherty                                  0        1
judge_groupCarol M Howard                                    0        1
judge_groupCatherine Marie Haberkorn                         0        1
judge_groupCharles P Burns                                   0        1
judge_groupColleen Ann Hyland                                0        1
judge_groupGeary W Kull                                      0        1
judge_groupJames B Linn                                      0        1
judge_groupJames Michael Obbish                              0        1
judge_groupJoseph  Cataldo                                   0        1
judge_groupJoseph Michael Claps                              0        1
judge_groupKenneth J Wadas                                   0        1
judge_groupLauren Gottainer Edidin                           0        1
judge_groupLawrence Edward Flood                             0        1
judge_groupMary Margaret Brosnahan                           0        1
judge_groupMichele M Pitman                                  0        1
judge_groupNeera  Walsh                                      0        1
judge_groupNicholas R Ford                                   0        1
judge_groupShelley  Sutker-Dermer                            0        1
judge_groupStanley  Sacks                                    0        1
judge_groupThaddeus L Wilson                                 0        1
judge_groupThomas J Hennelly                                 0        1
judge_groupVincent M Gaughan                                 0        1
judge_groupWilliam H Hooks                                   0        1
judge_groupWilliam T O'Brien                                 0        1
judge_groupOther judges                                      0        1
sentencing_year_num                                          0        1

Residual standard error: 0.3161 on 190139 degrees of freedom
Multiple R-squared:  7.144e-29, Adjusted R-squared:  -0.000405 
F-statistic: 1.764e-25 on 77 and 190139 DF,  p-value: 1</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> Residual Standard Error (0.3161): This measures the average deviation of the residuals from the regression line. A small value indicates that the residuals are close to zero, which is expected if the Zero Conditional Mean assumption holds.</p>
<p>Multiple R-squared (7.144e-29): This value is effectively zero, meaning that the independent variables explain almost none of the variation in the residuals. This supports the assumption that the residuals are uncorrelated with the predictors.</p>
<p>Adjusted R-squared (-0.000405): The negative value arises because the model’s explanatory power is so low that adding predictors reduces the adjusted R-squared. This further confirms that the predictors do not explain the residuals.</p>
<p>F-statistic (1.764e-25) and p-value (1): The F-statistic tests whether the predictors collectively explain a significant amount of variation in the residuals. The extremely small F-statistic and p-value of 1 indicate that the predictors have no significant relationship with the residuals.</p>
</section>
</section>
</section>
<section id="conclusions" class="level1">
<h1>5. Conclusions</h1>
<section id="a-implications-of-this-model" class="level2">
<h2 class="anchored" data-anchor-id="a-implications-of-this-model">5(a) Implications of this model</h2>
<p>The model demonstrates that sentence length in Cook County is highly predictable using legally relevant case characteristics such as offense type, charge class, and sentence type, which account for the majority of variation in sentencing outcomes. At the same time, the analysis shows that judicial assignment and defendant demographics remain systematically associated with sentence length even after conditioning on observable case factors. This suggests that sentencing outcomes reflect not only statutory and procedural considerations, but also institutional and demographic patterns that are not fully captured by case-level variables alone.</p>
<p>Importantly, the model’s predictive strength does not imply causal relationships. Rather, it highlights where unexplained variation persists, particularly for longer sentences, which are likely influenced by factors absent from the data such as criminal history, plea negotiations, guideline departures, and case-specific aggravating circumstances. The results therefore underscore both the explanatory power and the limitations of administrative sentencing data.</p>
</section>
<section id="b-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="b-recommendations">5(b) Recommendations</h2>
<p>My reccomendations to the Cook County State’s Attorney’s Office are mainly to look into the disparities in sentencing outcomes based on race. Although this analysis is descriptive and not causal, the possibilty of systematic differences in sentencing by race warrants further investigation. I would recommend conducting more detailed analyses that incorporate additional controls for prior criminal history, plea status, and guideline ranges to better isolate these associations. Additionally, exploring judge assignment mechanisms and their impact on sentencing could help identify potential sources of unwarranted variation. Finally, looking at how this trend has evolved over time is an essential piece in understanding whether policy changes or reforms have influenced sentencing equity.</p>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">5(d)</h2>
<p>This class has been a refreshing one: many times I feel that college courses focus too heavily on theory and not enough on practical application. This course struck a great balance between the two, allowing me to both understand the theoretical underpinnings of predictive modeling while also getting hands-on experience implementing models in R. The assignments were challenging but manageable, and I appreciated the opportunity to work with real-world datasets. Overall, I feel much more confident in my ability to conduct data analysis and build predictive models after taking this class.</p>
<p>Even though I have some prior experience with R and statistics, this course helped me solidify my understanding of key concepts, especially in model testing, an essential skill in today’s world. The lectures were clear and well-organized, I also enjoyed the collaborative aspects of the class, such as group test-prep and project reviews, which allowed me to learn from my classmates and see different approaches to problem-solving. Thank you!!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>